<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\OmniLyrics.Core\OmniLyrics.Core.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Scripts/AppleEvents.js" />
        <InternalsVisibleTo Include="MacBackendSmoke" />
    </ItemGroup>
</Project>
