<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><SelfContained>true</SelfContained></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/OmniLyrics.Gui/OmniLyrics.Gui.csproj" /></ItemGroup>
</Project>
