<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ApplicationIcon>../OmniLyrics.Gui/Assets/app.ico</ApplicationIcon>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SelfContained>true</SelfContained>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\OmniLyrics.BackendFactory\OmniLyrics.BackendFactory.csproj"/>
    </ItemGroup>

</Project>
